# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

from pytest_base_class import WebDriverSetup # new import!

class TestExample(WebDriverSetup):
    ''' in order for test to work with Selenium Bandaid, remove/comment setup_method()
        or call super().setup_method(method) inside it to ensure self.driver is set up
        Then TestExample should inherit from pytest_base_class.WebDriverSetup
    '''
    # def setup_method(self, method):
    #   self.driver = webdriver.Chrome()
    #   self.vars = {}
  
    def teardown_method(self, method):
        ''' no need to comment this method out, but you can '''
        self.driver.quit()
  
    def test_example(self):
        # Test name: example
        # Step # | name | target | value
        # 1 | open | / | 
        self.driver.get("https://www.google.com/")
        # 2 | setWindowSize | 1024x768 | 
        self.driver.set_window_size(1024, 768)
        # 3 | click | xpath=//textarea | 
        self.driver.find_element(By.XPATH, "//textarea").click()
        # 4 | type | xpath=//textarea | example typing into box
        self.driver.find_element(By.XPATH, "//textarea").send_keys("example typing into box")


        # self.driver.find_element(By.XPATH, "//div[4]/center/input").click()  # clicking the search box failed because it was obscured by suggestions drop-down
        # so instead hit ENTER key.
        # sometimes you need to hit RETURN key
        # or submit the form


        # these are KLUDGES that I had to add manually.
        self.driver.find_element(By.XPATH, "//textarea").send_keys(Keys.ENTER)
        try:
            self.driver.find_element(By.XPATH, "//textarea").send_keys(Keys.RETURN)
            self.driver.find_element(By.XPATH, "//textarea").submit()
        except:
            pass


        # 6 | pause | 1 | 
        time.sleep(2)  # just a sleep so you don't lose track of it
  
